### ISSUE TITLE
Cannot get the sensor information of HSR on Rviz

### ISSUE THREAD

**Issue by ayakasakurai0213** [hsr-project/hsr_ros2_doc#3]
__I'm trying to create a map in the simulator of HSR in ROS2 environment.
So I need to get the sensor information of HSR on Rviz.

I built a simulator according to [https://github.com/hsr-project/hsr_ros2_doc](url).
Then starting gazebo and spawning HSR worked correctly.

I ran the following command and started slam_toolbox.
`ros2 launch hsrb_mapping slam_toolbox_mapping.launch.py`
Then I started rviz and tried to create a map, but it failed to create it and said "no map recived".

I checked the active topics with the following command.
`ros2 topic list`
According to it, the base_link topic was not active.
Therefore Rviz cannot get the sensor infomation.
How can I make the base_link topic active?
Please advise.

**Comment by k-takeshita** [comment]
Does it mean that the /scan topic is not appearing?
Have you installed gazebo_ros_pkgs?

**Comment by ayakasakurai0213** [comment]
![image](https://github.com/hsr-project/hsr_ros2_doc/assets/107175167/8a4213f4-a522-4efe-8ea1-a70bac396ebc)
Thank you for your help.
I installed gazebo_ros_pkgs and was able to  get the HSR sensor infomation on Rviz.
However, Rviz displayed "no map recived" and failed to create the map.
The sensor information was not  the cause of it.
I am looking for a way to create a map.
If you know how to do it, please advise.

**Comment by k-takeshita** [comment]
In my setup, executing "ros2 launch hsrb_mapping slam_toolbox_mapping.launch.py" resulted in the display of red points from the laser, and the /map topic was also published.
However, there were instances where the /map topic was not produced.
In such cases, I found it often effective to shut down all nodes, execute "ros2 daemon stop" and "ros2 daemon start", and then relaunch the nodes.

**Comment by ayakasakurai0213** [comment]
Thanks for your reply.
Sorry, I solved myself.
I succeeded in creating the map.
I found the cause of the problem.
I had remapped the /scan topic in the launch file to create the map.
Therefore, map server could not get the sensor information.
![image](https://github.com/hsr-project/hsr_ros2_doc/assets/107175167/a9ec4a9c-7fd1-451d-9cc9-c0210ee87dac)
