### ISSUE TITLE
rosdep error on actual robot

### ISSUE THREAD

**Issue by ayakasakurai0213** [hsr-project/hsr_ros2_doc#4]
I built the ROS2 environment on the actual robot according to [https://github.com/hsr-project/hsr_ros2_doc](url).
I ran the following command.
`rosdep install --from-paths . -y --ignore-src`
And then, the following error is displayed.

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
hsrb_gripper_controller: Cannot locate rosdep definition for [joint_trajectory_controller]
openni2_camera: Cannot locate rosdep definition for [camera_info_manager]
hsrb_description: Cannot locate rosdep definition for [xacro]
hsrb_robot_hardware: Cannot locate rosdep definition for [transmission_interface]
hsrb_base_controllers: Cannot locate rosdep definition for [realtime_tools]
hsrb_bringup: Cannot locate rosdep definition for [usb_cam]

What is the solution?
Please advice.

**Comment by k-takeshita** [comment]
Have you already executed "rosdep init" and "rosdep update"?
Also, are you able to install joint_trajectory_controller and others using "apt install"?

**Comment by ayakasakurai0213** [comment]
Thank you for your help.
I've installed packages such as joint_trajectory_controller.
I was able to run the rosdep command.
